import type { GlassPreset } from '../glass/types'
import { GlassPresetDefinition } from './base'

export class PanelPreset extends GlassPresetDefinition {
  readonly id = 'panel'
  readonly config: GlassPreset = {
    shapeType: 1,
    surfaceType: 'convex-squircle',
    bezelWidth: 29,
    glassThickness: 90,
    refractiveIndex: 1.3,
    magnifyingScale: 0,
    circleSize: 1,
    rectWidth: 640,
    rectHeight: 63,
    rectRadiusPercent: 100,
    switchTrackWidth: 184,
    switchTrackHeight: 67,
    switchTrackOffOpacity: 0.34,
    switchTrackOnOpacity: 0.86,
    maxDisplacementScale: 4.0,
    trackProgress: 1,
    scaleRatio: 1,
    blurAmount: 0,
    blurType: 0,
    progressiveBlur: 0,
    progressiveBlurType: 0,
    glassBgOpacity: 0.96,
    pressedGlassBgOpacity: 0,
    specularType: 0,
    specularOpacity: 0.35,
    specularAngle: 60,
    specularSaturation: 4,
    shadowOpacity: 0.1,
    shadowBlur: 24,
    shadowOffsetX: 0,
    shadowOffsetY: 8,
    liquidPressScale: 1.08,
    liquidPressRefraction: 1.35,
    liquidClickSquash: 1,
    liquidDragSquash: 1,
    liquidReleaseSquash: 1,
    liquidSpeed: 1,
  }
}
