import type { GlassPreset } from '../glass/types'
import { GlassPresetDefinition } from './base'

export class SliderPreset extends GlassPresetDefinition {
  readonly id = 'slider'
  readonly config: GlassPreset = {
    shapeType: 1,
    surfaceType: 'convex-squircle',
    bezelWidth: 16,
    glassThickness: 80,
    refractiveIndex: 1.45,
    magnifyingScale: 0,
    circleSize: 0.6,
    rectWidth: 90,
    rectHeight: 60,
    rectRadiusPercent: 100,
    switchTrackWidth: 330,
    switchTrackHeight: 14,
    switchTrackOffOpacity: 0.4,
    switchTrackOnOpacity: 0.95,
    maxDisplacementScale: 4.0,
    trackProgress: 0.1,
    scaleRatio: 1.0,
    blurAmount: 0,
    blurType: 0,
    progressiveBlur: 0,
    progressiveBlurType: 0,
    glassBgOpacity: 0.92,
    pressedGlassBgOpacity: 0,
    specularType: 0,
    specularOpacity: 0.4,
    specularAngle: 60,
    specularSaturation: 7,
    shadowOpacity: 0.1,
    shadowBlur: 20,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    liquidPressScale: 1.67,
    liquidPressRefraction: 2.25,
    liquidClickSquash: 0.9,
    liquidDragSquash: 1,
    liquidReleaseSquash: 0.9,
    liquidSpeed: 1.1,
  }
}
